#!/bin/bash
# Integration Setup Manager
# Handles credential collection, validation, and storage for all integrations

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
ENV_FILE="$PROJECT_ROOT/.env.local"
PROJECT_MD="$PROJECT_ROOT/PROJECT.md"

# Plain text output (no color formatting)

# ============================================================================
# CREDENTIAL STORAGE
# ============================================================================

ensure_env_file() {
    if [[ ! -f "$ENV_FILE" ]]; then
        cat > "$ENV_FILE" << 'EOF'
# Multi-Agent Squad - Integration Credentials
# This file contains sensitive API keys and should NEVER be committed to git
# Generated by squad:init

EOF
        echo "Created $ENV_FILE"
    fi

    # Ensure .env.local is in .gitignore
    local gitignore="$PROJECT_ROOT/.gitignore"
    if [[ -f "$gitignore" ]]; then
        if ! grep -q "^\.env\.local$" "$gitignore" 2>/dev/null; then
            echo -e "\n# Integration credentials (never commit)\n.env.local" >> "$gitignore"
            echo "Added .env.local to .gitignore"
        fi
    else
        echo -e "# Integration credentials (never commit)\n.env.local" > "$gitignore"
        echo "Created .gitignore with .env.local"
    fi
}

save_credential() {
    local key="$1"
    local value="$2"

    ensure_env_file

    # Remove existing entry if present
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
        # macOS compatible sed
        sed -i '' "/^${key}=/d" "$ENV_FILE" 2>/dev/null || \
        sed -i "/^${key}=/d" "$ENV_FILE" 2>/dev/null
    fi

    # Add new entry
    echo "${key}=${value}" >> "$ENV_FILE"
}

load_credentials() {
    if [[ -f "$ENV_FILE" ]]; then
        set -a
        source "$ENV_FILE"
        set +a
    fi
}

# ============================================================================
# VALIDATION FUNCTIONS
# ============================================================================

validate_linear() {
    local api_key="$1"

    echo "Validating Linear API key..."

    local response=$(curl -s -w "\n%{http_code}" -X POST "https://api.linear.app/graphql" \
        -H "Authorization: $api_key" \
        -H "Content-Type: application/json" \
        -d '{"query": "{ viewer { id name email } }"}')

    local http_code=$(echo "$response" | tail -1)
    local body=$(echo "$response" | head -n -1)

    if [[ "$http_code" == "200" ]] && echo "$body" | grep -q '"viewer"'; then
        local user_name=$(echo "$body" | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4)
        local user_email=$(echo "$body" | grep -o '"email":"[^"]*"' | head -1 | cut -d'"' -f4)
        echo "Valid! Connected as: $user_name ($user_email)"
        return 0
    else
        echo "Invalid API key or connection failed"
        return 1
    fi
}

validate_jira() {
    local url="$1"
    local user="$2"
    local token="$3"

    echo "Validating Jira credentials..."

    # Remove trailing slash from URL
    url="${url%/}"

    local response=$(curl -s -w "\n%{http_code}" \
        -u "$user:$token" \
        "$url/rest/api/2/myself")

    local http_code=$(echo "$response" | tail -1)
    local body=$(echo "$response" | head -n -1)

    if [[ "$http_code" == "200" ]] && echo "$body" | grep -q '"displayName"'; then
        local display_name=$(echo "$body" | grep -o '"displayName":"[^"]*"' | head -1 | cut -d'"' -f4)
        echo "Valid! Connected as: $display_name"
        return 0
    else
        echo "Invalid credentials or connection failed (HTTP $http_code)"
        return 1
    fi
}

validate_slack() {
    local webhook_url="$1"

    echo "Validating Slack webhook..."

    local response=$(curl -s -w "\n%{http_code}" -X POST "$webhook_url" \
        -H "Content-Type: application/json" \
        -d '{"text": "Claude Squad integration test - you can ignore this message"}')

    local http_code=$(echo "$response" | tail -1)
    local body=$(echo "$response" | head -n -1)

    if [[ "$body" == "ok" ]]; then
        echo "Valid! Test message sent to Slack channel"
        return 0
    else
        echo "Invalid webhook URL or connection failed"
        return 1
    fi
}

validate_discord() {
    local webhook_url="$1"

    echo "Validating Discord webhook..."

    local response=$(curl -s -w "\n%{http_code}" -X POST "$webhook_url" \
        -H "Content-Type: application/json" \
        -d '{"content": "Claude Squad integration test - you can ignore this message"}')

    local http_code=$(echo "$response" | tail -1)

    if [[ "$http_code" == "204" || "$http_code" == "200" ]]; then
        echo "Valid! Test message sent to Discord channel"
        return 0
    else
        echo "Invalid webhook URL or connection failed (HTTP $http_code)"
        return 1
    fi
}

validate_github() {
    echo "Checking GitHub CLI authentication..."

    if command -v gh &> /dev/null; then
        if gh auth status &> /dev/null; then
            local user=$(gh api user -q '.login' 2>/dev/null || echo "unknown")
            echo "Valid! Authenticated via gh CLI as: $user"
            return 0
        else
            echo "GitHub CLI not authenticated. Run: gh auth login"
            return 1
        fi
    else
        echo "GitHub CLI (gh) not installed. Install from: https://cli.github.com"
        return 1
    fi
}

# ============================================================================
# SETUP FUNCTIONS
# ============================================================================

setup_linear() {
    echo ""
    echo "Linear Integration Setup"
    echo "Linear is a modern issue tracking tool for software teams."
    echo ""
    echo "To get your API key:"
    echo "  1. Go to https://linear.app/start-jur/settings/account/security"
    echo "  2. Click 'Create key'"
    echo "  3. Name it 'Claude Squad' and copy the key"
    echo ""

    read -p "Enter your Linear API key: " api_key

    if [[ -z "$api_key" ]]; then
        echo "Skipped Linear setup"
        return 1
    fi

    if validate_linear "$api_key"; then
        save_credential "LINEAR_API_KEY" "$api_key"
        update_project_tracking "linear"

        # Get default team
        echo "Fetching your Linear teams..."
        local teams=$(curl -s -X POST "https://api.linear.app/graphql" \
            -H "Authorization: $api_key" \
            -H "Content-Type: application/json" \
            -d '{"query": "{ teams { nodes { id name key } } }"}')

        local team_count=$(echo "$teams" | grep -o '"key":"[^"]*"' | wc -l | xargs)

        if [[ "$team_count" -gt 0 ]]; then
            echo "Found $team_count team(s). Default team will be used for issue creation."

            # Save first team as default
            local default_team=$(echo "$teams" | grep -o '"key":"[^"]*"' | head -1 | cut -d'"' -f4)
            save_credential "LINEAR_TEAM_KEY" "$default_team"
        fi

        return 0
    else
        return 1
    fi
}

setup_jira() {
    echo ""
    echo "Jira Integration Setup"
    echo "Jira is an enterprise issue tracking and project management tool."
    echo ""
    echo "You'll need:"
    echo "  1. Your Jira instance URL (e.g., https://yourcompany.atlassian.net)"
    echo "  2. Your email address"
    echo "  3. An API token from https://id.atlassian.com/manage-profile/security/api-tokens"
    echo ""

    read -p "Enter your Jira URL: " jira_url
    read -p "Enter your email: " jira_user
    read -sp "Enter your API token: " jira_token
    echo ""

    if [[ -z "$jira_url" || -z "$jira_user" || -z "$jira_token" ]]; then
        echo "Skipped Jira setup"
        return 1
    fi

    if validate_jira "$jira_url" "$jira_user" "$jira_token"; then
        save_credential "JIRA_URL" "$jira_url"
        save_credential "JIRA_USER" "$jira_user"
        save_credential "JIRA_TOKEN" "$jira_token"
        update_project_tracking "jira"

        # Get default project
        echo "Fetching your Jira projects..."
        local projects=$(curl -s -u "$jira_user:$jira_token" "$jira_url/rest/api/2/project")

        local project_count=$(echo "$projects" | grep -o '"key":"[^"]*"' | wc -l | xargs)

        if [[ "$project_count" -gt 0 ]]; then
            echo "Found $project_count project(s)."

            read -p "Enter the project key for issue creation (e.g., PROJ): " project_key
            if [[ -n "$project_key" ]]; then
                save_credential "JIRA_PROJECT_KEY" "$project_key"
            fi
        fi

        return 0
    else
        return 1
    fi
}

setup_slack() {
    echo ""
    echo "Slack Integration Setup"
    echo "Receive build, deploy, and PR notifications in Slack."
    echo ""
    echo "To get a webhook URL:"
    echo "  1. Go to https://api.slack.com/apps"
    echo "  2. Create a new app (or select existing)"
    echo "  3. Enable 'Incoming Webhooks'"
    echo "  4. Add a webhook to your workspace and copy the URL"
    echo ""

    read -p "Enter your Slack webhook URL: " webhook_url

    if [[ -z "$webhook_url" ]]; then
        echo "Skipped Slack setup"
        return 1
    fi

    if validate_slack "$webhook_url"; then
        save_credential "SLACK_WEBHOOK_URL" "$webhook_url"
        update_project_notifications "slack"
        return 0
    else
        return 1
    fi
}

setup_discord() {
    echo ""
    echo "Discord Integration Setup"
    echo "Receive build, deploy, and PR notifications in Discord."
    echo ""
    echo "To get a webhook URL:"
    echo "  1. Go to your Discord server settings"
    echo "  2. Navigate to Integrations > Webhooks"
    echo "  3. Create a new webhook and copy the URL"
    echo ""

    read -p "Enter your Discord webhook URL: " webhook_url

    if [[ -z "$webhook_url" ]]; then
        echo "Skipped Discord setup"
        return 1
    fi

    if validate_discord "$webhook_url"; then
        save_credential "DISCORD_WEBHOOK_URL" "$webhook_url"
        update_project_notifications "discord"
        return 0
    else
        return 1
    fi
}

setup_github() {
    echo ""
    echo "GitHub Integration Setup"
    echo "GitHub Issues uses the gh CLI for authentication."
    echo ""

    if validate_github; then
        update_project_tracking "github"
        return 0
    else
        echo ""
        echo -e "Would you like to authenticate now? (y/n)"
        read -r response
        if [[ "$response" =~ ^[Yy] ]]; then
            gh auth login
            if validate_github; then
                update_project_tracking "github"
                return 0
            fi
        fi
        return 1
    fi
}

# ============================================================================
# PROJECT.md UPDATES
# ============================================================================

update_project_tracking() {
    local provider="$1"

    if [[ ! -f "$PROJECT_MD" ]]; then
        return 0
    fi

    # Check if issue_tracking already exists
    if grep -q "^issue_tracking:" "$PROJECT_MD" 2>/dev/null; then
        # Update existing
        sed -i '' "s/^issue_tracking:.*/issue_tracking: $provider/" "$PROJECT_MD" 2>/dev/null || \
        sed -i "s/^issue_tracking:.*/issue_tracking: $provider/" "$PROJECT_MD" 2>/dev/null
    else
        # Add new
        echo -e "\nissue_tracking: $provider" >> "$PROJECT_MD"
    fi

    echo "Updated PROJECT.md with issue_tracking: $provider"
}

update_project_notifications() {
    local provider="$1"

    if [[ ! -f "$PROJECT_MD" ]]; then
        return 0
    fi

    # Check if notifications already exists
    if grep -q "^notifications:" "$PROJECT_MD" 2>/dev/null; then
        local current=$(grep "^notifications:" "$PROJECT_MD" | sed 's/notifications://' | xargs)
        if [[ ! "$current" =~ "$provider" ]]; then
            local new_value="$current, $provider"
            sed -i '' "s/^notifications:.*/notifications: $new_value/" "$PROJECT_MD" 2>/dev/null || \
            sed -i "s/^notifications:.*/notifications: $new_value/" "$PROJECT_MD" 2>/dev/null
        fi
    else
        echo -e "\nnotifications: $provider" >> "$PROJECT_MD"
    fi

    echo "Updated PROJECT.md with notifications: $provider"
}

# ============================================================================
# INTERACTIVE SETUP
# ============================================================================

setup_integration() {
    local integration="$1"

    case "$integration" in
        linear)
            setup_linear
            ;;
        jira)
            setup_jira
            ;;
        slack)
            setup_slack
            ;;
        discord)
            setup_discord
            ;;
        github|github-issues)
            setup_github
            ;;
        teams)
            echo "Microsoft Teams integration coming soon"
            return 1
            ;;
        email)
            echo "Email integration coming soon"
            return 1
            ;;
        *)
            echo "Unknown integration: $integration"
            return 1
            ;;
    esac
}

batch_setup() {
    local integrations=("$@")
    local success_count=0
    local fail_count=0

    echo ""
    echo "Setting up ${#integrations[@]} integration(s)..."
    echo ""

    for integration in "${integrations[@]}"; do
        echo "---------------------------------------------------"
        if setup_integration "$integration"; then
            ((success_count++))
        else
            ((fail_count++))
        fi
        echo ""
    done

    echo "---------------------------------------------------"
    echo ""
    echo "Integration Setup Complete"
    echo "  Successful: $success_count"
    if [[ $fail_count -gt 0 ]]; then
        echo "  Skipped/Failed: $fail_count"
    fi
    echo ""

    if [[ -f "$ENV_FILE" ]]; then
        echo "Credentials stored in: $ENV_FILE"
        echo "Remember: Never commit .env.local to git!"
    fi
}

status() {
    echo ""
    echo "Integration Status"
    echo ""

    load_credentials

    # Issue Tracking
    echo "Issue Tracking:"
    if [[ -n "$LINEAR_API_KEY" ]]; then
        echo "  Linear: Configured"
    fi
    if [[ -n "$JIRA_URL" && -n "$JIRA_USER" && -n "$JIRA_TOKEN" ]]; then
        echo "  Jira: Configured"
    fi
    if command -v gh &> /dev/null && gh auth status &> /dev/null 2>&1; then
        echo "  GitHub: Authenticated"
    fi

    # Notifications
    echo ""
    echo "Notifications:"
    if [[ -n "$SLACK_WEBHOOK_URL" ]]; then
        echo "  Slack: Configured"
    fi
    if [[ -n "$DISCORD_WEBHOOK_URL" ]]; then
        echo "  Discord: Configured"
    fi
    if [[ -n "$TEAMS_WEBHOOK_URL" ]]; then
        echo "  Teams: Configured"
    fi

    # Project config
    if [[ -f "$PROJECT_MD" ]]; then
        echo ""
        echo "Project Configuration (from PROJECT.md):"
        local tracking=$(grep "^issue_tracking:" "$PROJECT_MD" 2>/dev/null | sed 's/issue_tracking://' | xargs)
        local notifs=$(grep "^notifications:" "$PROJECT_MD" 2>/dev/null | sed 's/notifications://' | xargs)
        echo "  Issue Tracking: ${tracking:-not set}"
        echo "  Notifications: ${notifs:-not set}"
    fi

    echo ""
}

# ============================================================================
# MAIN
# ============================================================================

case "${1:-help}" in
    setup)
        shift
        if [[ $# -eq 0 ]]; then
            echo "Usage: setup-integration.sh setup <integration> [integration...]"
            echo "Available: linear, jira, github, slack, discord, teams, email"
            exit 1
        fi
        batch_setup "$@"
        ;;
    validate)
        shift
        integration="$1"
        load_credentials
        case "$integration" in
            linear) validate_linear "$LINEAR_API_KEY" ;;
            jira) validate_jira "$JIRA_URL" "$JIRA_USER" "$JIRA_TOKEN" ;;
            slack) validate_slack "$SLACK_WEBHOOK_URL" ;;
            discord) validate_discord "$DISCORD_WEBHOOK_URL" ;;
            github) validate_github ;;
            *) echo "Unknown integration: $integration" ;;
        esac
        ;;
    status)
        status
        ;;
    help|*)
        echo "Integration Setup Manager"
        echo ""
        echo "Usage: setup-integration.sh <command> [args]"
        echo ""
        echo "Commands:"
        echo "  setup <integrations...>  Set up one or more integrations"
        echo "  validate <integration>   Validate stored credentials"
        echo "  status                   Show integration status"
        echo ""
        echo "Integrations:"
        echo "  Issue Tracking: linear, jira, github"
        echo "  Notifications:  slack, discord, teams, email"
        echo ""
        echo "Examples:"
        echo "  setup-integration.sh setup linear slack"
        echo "  setup-integration.sh validate linear"
        echo "  setup-integration.sh status"
        ;;
esac
